#!/usr/bin/env python
import sys

env = Environment()
env.SetupCommandLineDebug()
env.SetupTCMalloc()
env.SetupMLFoundation()

env.FoundationProgram('tutorial1', ['tutorial1.m'])
env.FoundationProgram('tutorial2', ['tutorial2.m', 'Classes/Tutorial2Application.m'])
env.FoundationProgram('tutorial3', ['tutorial3.m', 'Classes/Tutorial3Application.m'])
env.FoundationProgram('tutorial4', ['tutorial4.m', 'Classes/Tutorial4Application.m'])
env.FoundationProgram('tutorial5', ['tutorial5.m', 'Classes/Tutorial5Application.m'])
env.FoundationProgram('tutorial6', ['tutorial6.m', 'Classes/Tutorial6Application.m'])

